// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET8API.Data;

#nullable disable

namespace NET8API.Migrations
{
    [DbContext(typeof(Net8ApiDbContext))]
    [Migration("20250814114032_Removed relationships")]
    partial class Removedrelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NET8API.Models.Domain.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ActualHours")
                        .HasColumnType("float");

                    b.Property<double>("EstimatedHours")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65472640-b37b-45c1-8f0b-7bbbb9ece3f3"),
                            ActualHours = 0.75,
                            EstimatedHours = 0.5,
                            Status = "In Progress",
                            TaskName = "Water the plants"
                        },
                        new
                        {
                            Id = new Guid("de47cc9d-e09e-425a-98b9-8a44698b399b"),
                            ActualHours = 0.75,
                            EstimatedHours = 1.0,
                            Status = "Done",
                            TaskName = "wash Dishes"
                        },
                        new
                        {
                            Id = new Guid("d822a934-263b-41b6-815a-adaedc5ee91e"),
                            ActualHours = 1.5,
                            EstimatedHours = 1.5,
                            Status = "Paused",
                            TaskName = "Do laundry"
                        });
                });

            modelBuilder.Entity("NET8API.Models.Domain.ToDoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
